<?php
namespace App\Support\Contabilidad;

/**
 * Plan Contable General Empresarial (PCGE, versión modificada 2019): todas las cuentas de 2 dígitos,
 * las divisionarias más usadas por un comercio y las subcuentas de 6 dígitos que usa la centralización automática.
 * La empresa puede agregar las subcuentas que necesite desde el Plan Contable.
 */
class Pcge
{
    public const CUENTAS = [
        // ===================== ELEMENTO 1: ACTIVO DISPONIBLE Y EXIGIBLE
        '10' => 'EFECTIVO Y EQUIVALENTES DE EFECTIVO',
        '101' => 'CAJA', '1011' => 'CAJA', '101101' => 'CAJA GENERAL',
        '102' => 'FONDOS FIJOS', '1021' => 'CAJA CHICA',
        '104' => 'CUENTAS CORRIENTES EN INSTITUCIONES FINANCIERAS', '1041' => 'CUENTAS CORRIENTES OPERATIVAS',
        '104101' => 'BANCO - CUENTA CORRIENTE MN', '104102' => 'BANCO - CUENTA CORRIENTE ME', '1042' => 'CUENTAS CORRIENTES PARA FINES ESPECÍFICOS',
        '107' => 'FONDOS SUJETOS A RESTRICCIÓN',
        '11' => 'INVERSIONES FINANCIERAS',
        '12' => 'CUENTAS POR COBRAR COMERCIALES - TERCEROS',
        '121' => 'FACTURAS, BOLETAS Y OTROS COMPROBANTES POR COBRAR', '1212' => 'EMITIDAS EN CARTERA', '121201' => 'FACTURAS Y BOLETAS POR COBRAR - EMITIDAS EN CARTERA',
        '122' => 'ANTICIPOS DE CLIENTES', '123' => 'LETRAS POR COBRAR',
        '13' => 'CUENTAS POR COBRAR COMERCIALES - RELACIONADAS',
        '14' => 'CUENTAS POR COBRAR AL PERSONAL, A LOS ACCIONISTAS (SOCIOS), DIRECTORES Y GERENTES',
        '141' => 'PERSONAL', '1411' => 'PRÉSTAMOS', '1413' => 'ENTREGAS A RENDIR CUENTA',
        '16' => 'CUENTAS POR COBRAR DIVERSAS - TERCEROS', '161' => 'PRÉSTAMOS', '162' => 'RECLAMACIONES A TERCEROS', '1629' => 'OTRAS',
        '17' => 'CUENTAS POR COBRAR DIVERSAS - RELACIONADAS',
        '18' => 'SERVICIOS Y OTROS CONTRATADOS POR ANTICIPADO', '181' => 'COSTOS FINANCIEROS', '182' => 'SEGUROS', '183' => 'ALQUILERES',
        '19' => 'ESTIMACIÓN DE CUENTAS DE COBRANZA DUDOSA',

        // ===================== ELEMENTO 2: ACTIVO REALIZABLE
        '20' => 'MERCADERÍAS', '201' => 'MERCADERÍAS', '2011' => 'MERCADERÍAS', '201111' => 'MERCADERÍAS - COSTO',
        '21' => 'PRODUCTOS TERMINADOS', '22' => 'SUBPRODUCTOS, DESECHOS Y DESPERDICIOS', '23' => 'PRODUCTOS EN PROCESO',
        '24' => 'MATERIAS PRIMAS', '241' => 'MATERIAS PRIMAS', '2411' => 'MATERIAS PRIMAS', '241111' => 'MATERIAS PRIMAS E INSUMOS',
        '25' => 'MATERIALES AUXILIARES, SUMINISTROS Y REPUESTOS', '252' => 'SUMINISTROS',
        '26' => 'ENVASES Y EMBALAJES', '27' => 'ACTIVOS NO CORRIENTES MANTENIDOS PARA LA VENTA', '28' => 'INVENTARIOS POR RECIBIR',
        '29' => 'DESVALORIZACIÓN DE INVENTARIOS',

        // ===================== ELEMENTO 3: ACTIVO INMOVILIZADO
        '30' => 'INVERSIONES MOBILIARIAS', '31' => 'PROPIEDADES DE INVERSIÓN', '32' => 'ACTIVOS POR DERECHO DE USO',
        '33' => 'PROPIEDADES, PLANTA Y EQUIPO', '331' => 'TERRENOS', '332' => 'EDIFICACIONES', '333' => 'MAQUINARIAS Y EQUIPOS DE EXPLOTACIÓN',
        '334' => 'UNIDADES DE TRANSPORTE', '335' => 'MUEBLES Y ENSERES', '3351' => 'MUEBLES', '336' => 'EQUIPOS DIVERSOS', '3361' => 'EQUIPO PARA PROCESAMIENTO DE INFORMACIÓN',
        '34' => 'INTANGIBLES', '343' => 'PROGRAMAS DE COMPUTADORA (SOFTWARE)', '35' => 'ACTIVOS BIOLÓGICOS', '36' => 'DESVALORIZACIÓN DE ACTIVO INMOVILIZADO',
        '37' => 'ACTIVO DIFERIDO', '38' => 'OTROS ACTIVOS',
        '39' => 'DEPRECIACIÓN, AMORTIZACIÓN Y AGOTAMIENTO ACUMULADOS', '391' => 'DEPRECIACIÓN ACUMULADA', '3913' => 'PROPIEDADES, PLANTA Y EQUIPO - COSTO',

        // ===================== ELEMENTO 4: PASIVO
        '40' => 'TRIBUTOS, CONTRAPRESTACIONES Y APORTES AL SISTEMA PÚBLICO DE PENSIONES Y DE SALUD POR PAGAR',
        '401' => 'GOBIERNO CENTRAL', '4011' => 'IMPUESTO GENERAL A LAS VENTAS', '40111' => 'IGV - CUENTA PROPIA', '401111' => 'IGV - CUENTA PROPIA',
        '4017' => 'IMPUESTO A LA RENTA', '40171' => 'RENTA DE TERCERA CATEGORÍA', '40172' => 'RENTA DE CUARTA CATEGORÍA', '40173' => 'RENTA DE QUINTA CATEGORÍA',
        '403' => 'INSTITUCIONES PÚBLICAS', '4031' => 'ESSALUD', '4032' => 'ONP',
        '407' => 'ADMINISTRADORAS DE FONDOS DE PENSIONES',
        '41' => 'REMUNERACIONES Y PARTICIPACIONES POR PAGAR', '411' => 'REMUNERACIONES POR PAGAR', '4111' => 'SUELDOS Y SALARIOS POR PAGAR',
        '415' => 'BENEFICIOS SOCIALES DE LOS TRABAJADORES POR PAGAR',
        '42' => 'CUENTAS POR PAGAR COMERCIALES - TERCEROS', '421' => 'FACTURAS, BOLETAS Y OTROS COMPROBANTES POR PAGAR', '4212' => 'EMITIDAS',
        '421201' => 'FACTURAS Y BOLETAS POR PAGAR - EMITIDAS', '422' => 'ANTICIPOS A PROVEEDORES', '423' => 'LETRAS POR PAGAR',
        '43' => 'CUENTAS POR PAGAR COMERCIALES - RELACIONADAS',
        '44' => 'CUENTAS POR PAGAR A LOS ACCIONISTAS (SOCIOS), DIRECTORES Y GERENTES',
        '45' => 'OBLIGACIONES FINANCIERAS', '451' => 'PRÉSTAMOS DE INSTITUCIONES FINANCIERAS Y OTRAS ENTIDADES',
        '46' => 'CUENTAS POR PAGAR DIVERSAS - TERCEROS', '469' => 'OTRAS CUENTAS POR PAGAR DIVERSAS',
        '47' => 'CUENTAS POR PAGAR DIVERSAS - RELACIONADAS', '48' => 'PROVISIONES', '49' => 'PASIVO DIFERIDO',

        // ===================== ELEMENTO 5: PATRIMONIO
        '50' => 'CAPITAL', '501' => 'CAPITAL SOCIAL', '5011' => 'ACCIONES', '5012' => 'PARTICIPACIONES',
        '51' => 'ACCIONES DE INVERSIÓN', '52' => 'CAPITAL ADICIONAL', '56' => 'RESULTADOS NO REALIZADOS', '57' => 'EXCEDENTE DE REVALUACIÓN',
        '58' => 'RESERVAS', '582' => 'LEGAL',
        '59' => 'RESULTADOS ACUMULADOS', '591' => 'UTILIDADES NO DISTRIBUIDAS', '5911' => 'UTILIDADES ACUMULADAS', '592' => 'PÉRDIDAS ACUMULADAS', '5921' => 'PÉRDIDAS ACUMULADAS',

        // ===================== ELEMENTO 6: GASTOS POR NATURALEZA
        '60' => 'COMPRAS', '601' => 'MERCADERÍAS', '6011' => 'MERCADERÍAS', '601111' => 'COMPRAS DE MERCADERÍAS',
        '602' => 'MATERIAS PRIMAS', '603' => 'MATERIALES AUXILIARES, SUMINISTROS Y REPUESTOS', '604' => 'ENVASES Y EMBALAJES',
        '609' => 'COSTOS VINCULADOS CON LAS COMPRAS', '6091' => 'COSTOS VINCULADOS CON LAS COMPRAS DE MERCADERÍAS',
        '61' => 'VARIACIÓN DE INVENTARIOS', '611' => 'MERCADERÍAS', '6111' => 'MERCADERÍAS', '611111' => 'VARIACIÓN DE MERCADERÍAS',
        '62' => 'GASTOS DE PERSONAL, DIRECTORES Y GERENTES', '621' => 'REMUNERACIONES', '6211' => 'SUELDOS Y SALARIOS',
        '627' => 'SEGURIDAD, PREVISIÓN SOCIAL Y OTRAS CONTRIBUCIONES', '6271' => 'RÉGIMEN DE PRESTACIONES DE SALUD',
        '629' => 'BENEFICIOS SOCIALES DE LOS TRABAJADORES',
        '63' => 'GASTOS DE SERVICIOS PRESTADOS POR TERCEROS', '631' => 'TRANSPORTE, CORREOS Y GASTOS DE VIAJE',
        '632' => 'ASESORÍA Y CONSULTORÍA', '634' => 'MANTENIMIENTO Y REPARACIONES', '635' => 'ALQUILERES',
        '636' => 'SERVICIOS BÁSICOS', '6361' => 'ENERGÍA ELÉCTRICA', '6363' => 'AGUA', '6364' => 'TELEFONÍA', '6365' => 'INTERNET',
        '637' => 'PUBLICIDAD, PUBLICACIONES, RELACIONES PÚBLICAS', '639' => 'OTROS SERVICIOS PRESTADOS POR TERCEROS',
        '64' => 'GASTOS POR TRIBUTOS', '641' => 'GOBIERNO CENTRAL', '643' => 'GOBIERNO LOCAL',
        '65' => 'OTROS GASTOS DE GESTIÓN', '651' => 'SEGUROS', '656' => 'SUMINISTROS', '659' => 'OTROS GASTOS DE GESTIÓN',
        '66' => 'PÉRDIDA POR MEDICIÓN DE ACTIVOS NO FINANCIEROS AL VALOR RAZONABLE',
        '67' => 'GASTOS FINANCIEROS', '673' => 'INTERESES POR PRÉSTAMOS Y OTRAS OBLIGACIONES', '676' => 'DIFERENCIA DE CAMBIO',
        '679' => 'OTROS GASTOS FINANCIEROS', '6791' => 'COMISIONES BANCARIAS Y DE MEDIOS DE PAGO',
        '68' => 'VALUACIÓN Y DETERIORO DE ACTIVOS Y PROVISIONES', '681' => 'DEPRECIACIÓN',
        '69' => 'COSTO DE VENTAS', '691' => 'MERCADERÍAS', '6911' => 'MERCADERÍAS', '691111' => 'COSTO DE VENTA DE MERCADERÍAS',

        // ===================== ELEMENTO 7: INGRESOS
        '70' => 'VENTAS', '701' => 'MERCADERÍAS', '7011' => 'MERCADERÍAS', '70111' => 'TERCEROS', '701111' => 'VENTA DE MERCADERÍAS - TERCEROS',
        '704' => 'PRESTACIÓN DE SERVICIOS', '7041' => 'TERCEROS', '709' => 'DEVOLUCIONES SOBRE VENTAS', '7091' => 'MERCADERÍAS',
        '71' => 'VARIACIÓN DE LA PRODUCCIÓN ALMACENADA', '72' => 'PRODUCCIÓN DE ACTIVO INMOVILIZADO',
        '73' => 'DESCUENTOS, REBAJAS Y BONIFICACIONES OBTENIDOS', '74' => 'DESCUENTOS, REBAJAS Y BONIFICACIONES CONCEDIDOS',
        '75' => 'OTROS INGRESOS DE GESTIÓN', '759' => 'OTROS INGRESOS DE GESTIÓN',
        '76' => 'GANANCIA POR MEDICIÓN DE ACTIVOS NO FINANCIEROS AL VALOR RAZONABLE',
        '77' => 'INGRESOS FINANCIEROS', '772' => 'RENDIMIENTOS GANADOS', '776' => 'DIFERENCIA DE CAMBIO',
        '78' => 'CARGAS CUBIERTAS POR PROVISIONES', '79' => 'CARGAS IMPUTABLES A CUENTAS DE COSTOS Y GASTOS',

        // ===================== ELEMENTO 8: SALDOS INTERMEDIARIOS DE GESTIÓN
        '80' => 'MARGEN COMERCIAL', '81' => 'PRODUCCIÓN DEL EJERCICIO', '82' => 'VALOR AGREGADO',
        '83' => 'EXCEDENTE BRUTO (INSUFICIENCIA BRUTA) DE EXPLOTACIÓN', '84' => 'RESULTADO DE EXPLOTACIÓN',
        '85' => 'RESULTADO ANTES DE PARTICIPACIONES E IMPUESTOS', '88' => 'IMPUESTO A LA RENTA',
        '89' => 'DETERMINACIÓN DEL RESULTADO DEL EJERCICIO', '891' => 'UTILIDAD', '892' => 'PÉRDIDA',

        // ===================== ELEMENTO 9: CONTABILIDAD ANALÍTICA DE EXPLOTACIÓN
        '90' => 'COSTOS DE PRODUCCIÓN', '94' => 'GASTOS ADMINISTRATIVOS', '95' => 'GASTOS DE VENTAS', '97' => 'GASTOS FINANCIEROS',
    ];

    /** Elemento → tipo y naturaleza del saldo */
    public static function tipo(string $cuenta): array
    {
        return match ($cuenta[0]) {
            '1', '2', '3' => ['ACTIVO', 'D'],
            '4' => ['PASIVO', 'A'],
            '5' => ['PATRIMONIO', 'A'],
            '6' => ['GASTO', 'D'],
            '7' => ['INGRESO', 'A'],
            '8' => ['RESULTADO', 'A'],
            '9' => ['ANALITICA', 'D'],
            default => ['ORDEN', 'D'],
        };
    }

    /** Filas listas para insertar en conta_plan */
    public static function filas(string $ruc): array
    {
        $ahora = now();
        $codigos = array_map('strval', array_keys(self::CUENTAS));
        return array_map(function ($c) use ($ruc, $ahora, $codigos) {
            [$tipo, $nat] = self::tipo($c);
            // Imputable: la que no tiene subcuentas debajo
            $hijas = array_filter($codigos, fn($x) => $x !== $c && str_starts_with($x, $c));
            return ['IdEmpresa' => $ruc, 'cuenta' => $c, 'descripcion' => self::CUENTAS[$c], 'nivel' => strlen($c),
                'tipo' => $tipo, 'naturaleza' => $nat, 'imputable' => empty($hijas) ? 1 : 0, 'estado' => 'Activo',
                'created_at' => $ahora, 'updated_at' => $ahora];
        }, $codigos);
    }
}
